import Head from "next/head";
import axios from "axios";
import SectionOne from "@/components/HomepageSections/SectionOne";
import SectionTwo from "@/components/HomepageSections/SectionTwo/SectionTwo";
import { useRouter } from "next/router";
import BaseHeading from "@/components/UI/BaseHeading";
import BasePageContainer from "@/components/UI/BasePageContainer";
import BaseDescription from "@/components/UI/BaseDescription";

export default function Home({ homeProps }) {
  const router = useRouter();
  const onChoosingSection = (section) => {
    router.push(section);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasePageContainer>
        <BaseHeading>Our Sections</BaseHeading>
        <nav className="flex w-full justify-end gap-5 pb-3">
          <button
            type="button"
            onClick={() => onChoosingSection("/?section=1")}
          >
            <div className="relative flex flex-col items-center gap-2">
              <BaseDescription className="hover:text-teal-300">
                Section 1
              </BaseDescription>
              <div
                className={`${
                  router.asPath === "/?section=1" || router.asPath === "/"
                    ? "absolute"
                    : "hidden"
                } top-8 h-2 w-2 rounded-full bg-teal-300`}
              />
            </div>
          </button>
          <button
            type="button"
            onClick={() => onChoosingSection("/?section=2")}
          >
            <div className="relative flex flex-col items-center gap-2">
              <BaseDescription className="hover:text-teal-300">
                Section 2
              </BaseDescription>
              <div
                className={`${
                  router.asPath === "/?section=2" ? "absolute" : "hidden"
                } top-8 h-2 w-2 rounded-full bg-teal-300`}
              />
            </div>
          </button>
        </nav>
        {(!router.query.section || router.query.section === "1") && (
          <SectionOne sectionProps={homeProps?.sections[0]} />
        )}
        {router.query.section === "2" && (
          <SectionTwo sectionProps={homeProps?.sections[1]} />
        )}
      </BasePageContainer>
    </>
  );
}

export async function getStaticProps() {
  let homeData;

  try {
    const resHome = await axios.get(process.env.NEXT_PUBLIC_HOME_API);
    homeData = resHome.data?.data;
  } catch (err) {
    console.log(err);
  }
  const homeProps = homeData ?? null;

  return {
    props: { homeProps },
  };
}
