import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useState } from "react";
import SectionOne from "@/components/HomepageSections/SectionOne";
import SectionTwo from "@/components/HomepageSections/SectionTwo/SectionTwo";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  menuProps,
  homeProps,
  sliderProps,
  section = 2,
}) {
  const [activeSection, setActiveSection] = useState(section);

  console.log("homepprops", homeProps);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full justify-center">
        <div className="flex w-full max-w-7xl flex-col items-center gap-5 py-10">
          <h2>Our Sections</h2>
          <nav className="flex w-full justify-end gap-5 bg-red-100">
            <button>Section 1</button>
            <button>Section 2</button>
          </nav>
          {activeSection === 1 && <SectionOne />}
          {activeSection === 2 && (
            <SectionTwo sectionProps={homeProps.sections[1]} />
          )}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  // const menuData = await axios.get(process.env.NEXT_PUBLIC_MENU_API)
  let menuData;
  let homeData;
  let sliderData;
  try {
    const resMenu = await axios.get(process.env.NEXT_PUBLIC_MENU_API);
    menuData = resMenu.data?.data;

    const resHome = await axios.get(process.env.NEXT_PUBLIC_HOME_API);
    homeData = resHome.data?.data;

    const resSlider = await axios.get(process.env.NEXT_PUBLIC_SLIDER_API);
    sliderData = resSlider.data?.data;
  } catch (err) {
    console.log(err);
  }
  const menuProps = menuData ?? null;
  const homeProps = homeData ?? null;
  const sliderProps = sliderData ?? null;

  return {
    props: { menuProps, homeProps, sliderProps },
  };
}
